### ISSUE TITLE
Support for RFC5222 XML with GML Elements

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [highsource/jsonix-support#7]
I tried to map the attached XML to a JavaScript object, but I totally failed. I just have troubles with the qualified names, everything else is working fine.

[findServicePolygonXML.txt](https://github.com/highsource/jsonix-support/files/46535/findServicePolygonXML.txt)
[findServiceXML.txt](https://github.com/highsource/jsonix-support/files/46536/findServiceXML.txt)

**Comment by highsource** [comment]
Please send me a pull request with the reproducing project. I need your schemas an how you compile them.

**Comment by highsource** [comment]
And generated mappings.
